#!/usr/bin/env node
/* eslint-disable no-console */
'use strict'; // eslint-disable-line strict

console.log('\x1b[1m', 'Please wait for tests to run...', '\x1b[0m');
console.log('You can', '\x1b[1m', 'skip', '\x1b[0m', 'the precommit hook by running "git commit -n" instead',
  '\x1b[1m', 'but beware!', '\x1b[0m');

require('child_process').exec(
  'npm test',
  (error, stdout) => {
    console.log(stdout && `stdout: ${stdout}`);

    if (error !== null) {
      console.log(error);
      process.abort(0); // eslint-disable-line no-magic-numbers
    }
  }
);

// credits to https://github.com/jrans/Node-Git-Hooks
